apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localstack-data-pvc
  namespace: localstack-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi