spring:
  application:
    name: ${APPLICATION_NAME:jossbee-image-server}
s3:
  accessKey: ${AWS_S3_ACCESS_KEY:team_jossBee}
  secretKey: ${AWS_S3_SECRET_KEY:team_jossBee}
  bucketName: ${AWS_S3_BUCKET:jossbee}