spring:
  application:
    name: ${APPLICATION_NAME:jossbee-image-server}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
s3:
  accessKey: ${AWS_S3_ACCESS_KEY:team_jossBee}
  secretKey: ${AWS_S3_SECRET_KEY:team_jossBee}
  bucketName: ${AWS_S3_BUCKET:jossbee}