version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth
      MYSQL_PASSWORD: auth_db
    ports:
      - "3306:3306"