spring:
  application:
    name: ${APPLICATION_NAME:jossbee-house-owner}
  data:
    mongodb:
      uri: mongodb+srv://jossbee:PE2jfY8235ongk95@cluster0.k8a4zdv.mongodb.net/jossbee?retryWrites=true&w=majority
house_topic: house_topic