spring:
  application:
    name: ${APPLICATION_NAME:jossbee-house-owner}
s3:
  host: ${S3_HOST:http://localhost:4566}
  accessKey: ${AWS_S3_ACCESS_KEY:team_jossBee}
  secretKey: ${AWS_S3_SECRET_KEY:team_jossBee}