apiVersion: v1
kind: Service
metadata:
  name: auth-server-nodeport-service
spec:
  selector:
    app: auth-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 9191
      targetPort: 9191
      nodePort: 31000
