apiVersion: v1
kind: Service
metadata:
  name: localstack-service
  namespace: localstack-namespace
spec:
  selector:
    app: localstack
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566
      name: service-port-1
    - protocol: TCP
      port: 4571
      targetPort: 4571
      name: service-port-2
  type: NodePort
