server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH}

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
      naming:
        physical-strategy: ${JPA_PHYSICAL_STRATEGY}
    properties:
      hibernate:
        show_sql: ${JPA_SHOW_SQL}
        format_sql: ${JPA_FORMAT_SQL}
        dialect: ${JPA_DIALECT}
    generate-ddl: ${JPA_GENERATE_DDL}
  application:
    name: ${APPLICATION_NAME}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_INCLUDE}
        exclude: ${MANAGEMENT_EXCLUDE}
